---
- name: Import MongoDB GPG key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-5.0.asc
    state: present 
- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/5.0 multiverse"
    state: present
- name: Update apt package cache
  apt:
    update_cache: yes
- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
- name: Start MongoDB service
  systemd:
    name: mongod
    state: started
    enabled: yes
