---
- name: Configure server
  hosts: all
  become: yes
  roles:
    - docker_add
    - apt_install
    - nvm_install
    - docker
    - ssh_init
    - nginx
    # - user_creation
    - git_clone
    - build_add
    - compose